- name: change route53
  route53:
    state: present
    zone: test.com
    record: www.test.com
    failover: SECONDARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "8e705f2e-dfc4-48e9-bc2c-f72ae2cb7a3e"
